"""Tests for branding helpers."""

import os
from unittest.mock import patch

import pytest

from schema_scraper.branding import (
    NO_BANNER_ENV_VAR,
    append_footer,
    format_banner,
    format_footer,
    is_branding_disabled,
    maybe_echo_banner,
)


class TestBrandingDisabled:
    """Tests for branding suppression."""

    def test_disabled_when_quiet(self):
        assert is_branding_disabled(quiet=True) is True

    def test_enabled_by_default(self):
        assert is_branding_disabled(quiet=False) is False

    @pytest.mark.parametrize("value", ["1", "true", "yes", "on", "TRUE"])
    def test_disabled_by_env_var(self, value: str):
        with patch.dict(os.environ, {NO_BANNER_ENV_VAR: value}):
            assert is_branding_disabled(quiet=False) is True

    def test_enabled_when_env_var_empty(self):
        with patch.dict(os.environ, {NO_BANNER_ENV_VAR: ""}, clear=False):
            assert is_branding_disabled(quiet=False) is False


class TestBrandingContent:
    """Tests for banner and footer formatting."""

    def test_format_banner_includes_company_and_version(self):
        banner = format_banner("1.2.3")
        assert "Phoenix DataWorks" in banner
        assert "schema-scraper v1.2.3" in banner

    def test_format_footer_includes_company_link(self):
        footer = format_footer("1.2.3")
        assert "schema-scraper v1.2.3" in footer
        assert "[Phoenix DataWorks](https://github.com/phoenixdataworks)" in footer

    def test_append_footer_adds_attribution(self):
        content = append_footer("# Title\n\nBody", quiet=False, version="1.0.0")
        assert content.startswith("# Title\n\nBody")
        assert "Generated by schema-scraper v1.0.0" in content

    def test_append_footer_respects_quiet(self):
        content = append_footer("# Title", quiet=True)
        assert content == "# Title"


class TestMaybeEchoBanner:
    """Tests for startup banner output."""

    def test_does_not_echo_when_quiet(self, capsys):
        with patch("sys.stdout.isatty", return_value=True):
            maybe_echo_banner(quiet=True)
        assert capsys.readouterr().out == ""

    def test_does_not_echo_when_not_tty(self, capsys):
        with patch("sys.stdout.isatty", return_value=False):
            maybe_echo_banner(quiet=False)
        assert capsys.readouterr().out == ""

    def test_echoes_banner_on_tty(self, capsys):
        with patch("sys.stdout.isatty", return_value=True):
            maybe_echo_banner(quiet=False, version="9.9.9")
        output = capsys.readouterr().out
        assert "Phoenix DataWorks" in output
        assert "schema-scraper v9.9.9" in output
