"""Branding helpers for CLI output and generated documentation."""

import os
import sys

import click

from . import __version__

COMPANY_NAME = "Phoenix DataWorks"
COMPANY_URL = "https://github.com/phoenixdataworks"
NO_BANNER_ENV_VAR = "SCHEMA_SCRAPER_NO_BANNER"


def is_branding_disabled(*, quiet: bool = False) -> bool:
    """Return True when branding should be suppressed."""
    if quiet:
        return True
    return os.environ.get(NO_BANNER_ENV_VAR, "").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def format_banner(version: str = __version__) -> str:
    """Return a compact startup banner for interactive terminals."""
    return (
        "╔═══════════════════════════════════════╗\n"
        f"║   {COMPANY_NAME:<33} ║\n"
        f"║   schema-scraper v{version:<20} ║\n"
        "╚═══════════════════════════════════════╝"
    )


def format_footer(version: str = __version__) -> str:
    """Return a one-line attribution footer for generated markdown."""
    return (
        f"\n---\n"
        f"*Generated by schema-scraper v{version} · "
        f"[{COMPANY_NAME}]({COMPANY_URL})*"
    )


def append_footer(content: str, *, quiet: bool = False, version: str = __version__) -> str:
    """Append the branding footer when branding is enabled."""
    if is_branding_disabled(quiet=quiet):
        return content
    return content.rstrip() + format_footer(version)


def maybe_echo_banner(*, quiet: bool = False, version: str = __version__) -> None:
    """Print the startup banner for interactive terminal sessions."""
    if is_branding_disabled(quiet=quiet):
        return
    if not sys.stdout.isatty():
        return

    click.echo(format_banner(version))
    click.echo("")
