-- Oracle Test Schema for Schema Scraper
-- Contains 1-2 objects of each supported type
-- Runs as TESTUSER in Oracle Free container

-- =============================================================================
-- SEQUENCES
-- =============================================================================
CREATE SEQUENCE order_seq
    START WITH 1000
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999
    CACHE 10;

CREATE SEQUENCE product_seq
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

-- =============================================================================
-- USER-DEFINED TYPES
-- =============================================================================
-- Object type
CREATE OR REPLACE TYPE address_type AS OBJECT (
    street VARCHAR2(200),
    city VARCHAR2(100),
    state VARCHAR2(50),
    postal_code VARCHAR2(20),
    country VARCHAR2(50)
);
/

-- =============================================================================
-- TABLES
-- =============================================================================
CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    phone VARCHAR2(20),
    shipping_address address_type,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
);

CREATE INDEX idx_customers_name ON customers (last_name, first_name);
CREATE INDEX idx_customers_email ON customers (email);

COMMENT ON TABLE customers IS 'Customer master table containing contact and shipping information';
COMMENT ON COLUMN customers.customer_id IS 'Unique customer identifier';
COMMENT ON COLUMN customers.email IS 'Customer email address (unique)';

CREATE TABLE products (
    product_id NUMBER DEFAULT product_seq.NEXTVAL PRIMARY KEY,
    sku VARCHAR2(50) NOT NULL UNIQUE,
    name VARCHAR2(200) NOT NULL,
    description CLOB,
    unit_price NUMBER(10,2) NOT NULL CHECK (unit_price > 0),
    quantity_in_stock NUMBER NOT NULL DEFAULT 0 CHECK (quantity_in_stock >= 0),
    reorder_level NUMBER DEFAULT 10,
    category VARCHAR2(100),
    is_discontinued NUMBER(1) DEFAULT 0 CHECK (is_discontinued IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_products_category ON products (category);
CREATE INDEX idx_products_sku ON products (sku);

COMMENT ON TABLE products IS 'Product catalog with inventory tracking';

CREATE TABLE orders (
    order_id NUMBER DEFAULT order_seq.NEXTVAL PRIMARY KEY,
    customer_id NUMBER NOT NULL REFERENCES customers(customer_id),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    total_amount NUMBER(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    notes CLOB
);

CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_date ON orders (order_date DESC);
CREATE INDEX idx_orders_status ON orders (status);

COMMENT ON TABLE orders IS 'Customer orders with status tracking';

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id NUMBER NOT NULL REFERENCES products(product_id),
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    unit_price NUMBER(10,2) NOT NULL CHECK (unit_price > 0),
    discount_percent NUMBER(5,2) DEFAULT 0 CHECK (discount_percent >= 0 AND discount_percent <= 100),
    CONSTRAINT uk_order_product UNIQUE (order_id, product_id)
);

-- =============================================================================
-- VIEWS
-- =============================================================================
CREATE OR REPLACE VIEW customer_order_summary AS
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.email,
    COUNT(o.order_id) AS total_orders,
    NVL(SUM(o.total_amount), 0) AS lifetime_value,
    MAX(o.order_date) AS last_order_date
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.email;

CREATE OR REPLACE VIEW low_stock_products AS
SELECT
    product_id,
    sku,
    name,
    quantity_in_stock,
    reorder_level,
    reorder_level - quantity_in_stock AS units_to_order
FROM products
WHERE quantity_in_stock < reorder_level
  AND is_discontinued = 0;

-- =============================================================================
-- FUNCTIONS
-- =============================================================================
CREATE OR REPLACE FUNCTION calculate_order_total(p_order_id IN NUMBER)
RETURN NUMBER
IS
    v_total NUMBER(12,2);
BEGIN
    SELECT NVL(SUM(quantity * unit_price * (1 - discount_percent/100)), 0)
    INTO v_total
    FROM order_items
    WHERE order_id = p_order_id;

    RETURN v_total;
END calculate_order_total;
/

CREATE OR REPLACE FUNCTION get_customer_name(p_customer_id IN NUMBER)
RETURN VARCHAR2
IS
    v_name VARCHAR2(100);
BEGIN
    SELECT first_name || ' ' || last_name
    INTO v_name
    FROM customers
    WHERE customer_id = p_customer_id;

    RETURN v_name;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END get_customer_name;
/

-- =============================================================================
-- STORED PROCEDURES
-- =============================================================================
CREATE OR REPLACE PROCEDURE create_order(
    p_customer_id IN NUMBER,
    p_notes IN CLOB DEFAULT NULL,
    p_order_id OUT NUMBER
)
AS
BEGIN
    INSERT INTO orders (customer_id, notes, total_amount)
    VALUES (p_customer_id, p_notes, 0)
    RETURNING order_id INTO p_order_id;

    COMMIT;
END create_order;
/

CREATE OR REPLACE PROCEDURE update_stock(
    p_product_id IN NUMBER,
    p_quantity_change IN NUMBER
)
AS
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM products WHERE product_id = p_product_id;

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Product not found');
    END IF;

    UPDATE products
    SET quantity_in_stock = quantity_in_stock + p_quantity_change
    WHERE product_id = p_product_id;

    COMMIT;
END update_stock;
/

-- =============================================================================
-- TRIGGERS
-- =============================================================================
CREATE OR REPLACE TRIGGER trg_customers_update_timestamp
BEFORE UPDATE ON customers
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_order_items_update_total
AFTER INSERT OR UPDATE OR DELETE ON order_items
FOR EACH ROW
DECLARE
    v_order_id NUMBER;
BEGIN
    IF INSERTING OR UPDATING THEN
        v_order_id := :NEW.order_id;
    ELSE
        v_order_id := :OLD.order_id;
    END IF;

    UPDATE orders
    SET total_amount = calculate_order_total(v_order_id)
    WHERE order_id = v_order_id;
END;
/

-- =============================================================================
-- SYNONYMS
-- =============================================================================
CREATE OR REPLACE SYNONYM prods FOR products;
CREATE OR REPLACE SYNONYM custs FOR customers;

-- =============================================================================
-- SAMPLE DATA
-- =============================================================================
INSERT INTO customers (email, first_name, last_name, phone) VALUES
    ('john.doe@example.com', 'John', 'Doe', '555-0101');
INSERT INTO customers (email, first_name, last_name, phone) VALUES
    ('jane.smith@example.com', 'Jane', 'Smith', '555-0102');

INSERT INTO products (sku, name, description, unit_price, quantity_in_stock, category) VALUES
    ('WIDGET-001', 'Standard Widget', 'A basic widget for everyday use', 19.99, 100, 'Widgets');
INSERT INTO products (sku, name, description, unit_price, quantity_in_stock, category) VALUES
    ('WIDGET-002', 'Premium Widget', 'A high-quality premium widget', 49.99, 50, 'Widgets');
INSERT INTO products (sku, name, description, unit_price, quantity_in_stock, category) VALUES
    ('GADGET-001', 'Mini Gadget', 'Compact and portable gadget', 29.99, 75, 'Gadgets');

COMMIT;
